name: xlnblog
on:
  push:
    branches:
      - main
jobs:
  deploy:
#    runs-on: ubuntu-20.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
#          hugo-version: "latest" # 可以修改为你使用的 Hugo 版本
          hugo-version: "0.141.0" #
          extended: true # 设置是否需要 extended 版本

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 另外还支持 deploy_token 和 github_token
          external_repository: xln3/xln3.github.io.git # 修改为你的 GitHub Pages 仓库
          publish_dir: ./public
          publish_branch: main
